# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('protein', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mfp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MfpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfpData', to='snippets.Mfp')),
                ('goals', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.Goals')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('protein', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mfpdata',
            name='totals',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='snippets.Totals'),
        ),
    ]
