# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiber', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='snippets.MfpData')),
            ],
        ),
    ]
