# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20180803_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='caloriesa',
            new_name='calories',
        ),
    ]
