version: '3'

services:
  fitdash-django:
    build: fitdash-django
    command: python tutorial/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./config.env:/config.env
      - ./fitdash-django/tutorial:/app/tutorial
    ports:
      - 8000:8000

  fitdash-api:
    build: fitdash-api
    command: npm run devstart
    volumes:
      - ./fitdash-api/tutorial:/app/tutorial
    ports:
      - 3011:3011
    depends_on: 
      - mongodb

  mongodb:
    image: mongo:latest
    volumes:
      - ./fitdash-api/data/db:/data/db
    ports:
        - 27017:27017
    command: mongod

  fitdash-app:
    build: fitdash-app
    command: npm start
    ports:
      - 3100:3100