version: '3'

services:
  fitdash-django:
    build: fitdash-django
    command: python tutorial/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./config.env:/config.env
    ports:
      - 8000:8000
  fitdash-api:
    build: fitdash-api
    command: npm run devstart
    ports:
      - 3011:3011
  mongodb:
    image: mongo:latest
    volumes:
      - ./fitdash-api/data/db:/data/db
    ports:
        - 27017:27017
    command: mongod
  fitdash-app:
    build: fitdash-app
    command: npm start
    volumes:
      - ./fitdash-app:/usr/src/app
    ports:
      - 3100:3100